// src/lib/mockData.ts
import type { AnomalyTag, Category, Machine, User } from "@/types";

export const mockCategories: Category[] = [
  {
    id: "1",
    code: "A",
    name: "Mechanical Failure",
    description: "Issues with mechanical components",
    examples: "Bearing failure, belt breakage, gear damage",
  },
  {
    id: "2",
    code: "B",
    name: "Electrical Issue",
    description: "Problems with electrical systems",
    examples: "Motor failure, wiring issues, sensor malfunction",
  },
  {
    id: "3",
    code: "C",
    name: "Hydraulic Leak",
    description: "Leaks in hydraulic systems",
    examples: "Oil leak, pressure loss, hose failure",
  },
  {
    id: "4",
    code: "D",
    name: "Pneumatic Issue",
    description: "Issues with pneumatic systems",
    examples: "Air leak, cylinder failure, valve stuck",
  },
  {
    id: "5",
    code: "E",
    name: "Quality Defect",
    description: "Product quality issues",
    examples: "Surface defect, dimension out of spec, contamination",
  },
  {
    id: "6",
    code: "F",
    name: "Safety Hazard",
    description: "Safety concerns",
    examples: "Missing guard, unsafe condition, chemical spill",
  },
];

export const mockMachines: Machine[] = [
  {
    id: "1",
    name: "Assembly Line A",
    code: "ASM-A-01",
    department: "Assembly",
  },
  {
    id: "2",
    name: "CNC Machine 101",
    code: "CNC-101",
    department: "Machining",
  },
  {
    id: "3",
    name: "Packaging Machine",
    code: "PKG-01",
    department: "Packaging",
  },
  {
    id: "4",
    name: "Conveyor Belt System",
    code: "CVY-01",
    department: "Material Handling",
  },
  { id: "5", name: "Injection Molding", code: "INJ-01", department: "Molding" },
  { id: "6", name: "Robotic Arm", code: "RBT-01", department: "Automation" },
];

export const mockUsers: User[] = [
  {
    id: "1",
    name: "John Operator",
    email: "john@factory.com",
    role: "Operator",
    department: "Production",
  },
  {
    id: "2",
    name: "Sarah Smith",
    email: "sarah@factory.com",
    role: "Production Supervisor",
    department: "Production",
  },
  {
    id: "3",
    name: "Mike Maintenance",
    email: "mike@factory.com",
    role: "Maintenance Supervisor",
    department: "Maintenance",
  },
  {
    id: "4",
    name: "Lisa Quality",
    email: "lisa@factory.com",
    role: "Quality Coordinator",
    department: "Quality",
  },
  {
    id: "5",
    name: "Tom CI",
    email: "tom@factory.com",
    role: "Continuous Improvement",
    department: "CI",
  },
  {
    id: "6",
    name: "Admin User",
    email: "admin@factory.com",
    role: "Administrator",
    department: "IT",
  },
];

export const mockTags: AnomalyTag[] = [
  {
    id: "1",
    tagId: "ANO-20260321-0001",
    category: "1",
    categoryName: "Mechanical Failure",
    machineId: "1",
    machineName: "Assembly Line A",
    description:
      "Conveyor belt making unusual grinding noise. Need immediate inspection.",
    priority: "Critical",
    status: "In Progress",
    pillar: "Safety",
    createdBy: "1",
    createdByUserName: "John Operator",
    createdAt: "2026-03-21T08:30:00",
    assignedTo: "3",
    assignedToUserName: "Mike Maintenance",
    assignedAt: "2026-03-21T09:00:00",
    photos: [],
  },
  {
    id: "2",
    tagId: "ANO-20260321-0002",
    category: "5",
    categoryName: "Quality Defect",
    machineId: "2",
    machineName: "CNC Machine 101",
    description:
      "Parts coming out with surface scratches. Check tooling condition.",
    priority: "High",
    status: "Open",
    pillar: "Quality",
    createdBy: "1",
    createdByUserName: "John Operator",
    createdAt: "2026-03-21T10:15:00",
    photos: [],
  },
  {
    id: "3",
    tagId: "ANO-20260320-0003",
    category: "3",
    categoryName: "Hydraulic Leak",
    machineId: "5",
    machineName: "Injection Molding",
    description: "Hydraulic oil leak detected near pump. Oil level dropping.",
    priority: "High",
    status: "Pending Parts",
    pillar: "Cost",
    createdBy: "1",
    createdByUserName: "John Operator",
    createdAt: "2026-03-20T14:00:00",
    assignedTo: "3",
    assignedToUserName: "Mike Maintenance",
    assignedAt: "2026-03-20T14:30:00",
    photos: [],
  },
  {
    id: "4",
    tagId: "ANO-20260320-0002",
    category: "2",
    categoryName: "Electrical Issue",
    machineId: "3",
    machineName: "Packaging Machine",
    description: "Machine randomly shuts down. Error code E-102 displayed.",
    priority: "Medium",
    status: "Completed",
    pillar: "Delivery",
    createdBy: "1",
    createdByUserName: "John Operator",
    createdAt: "2026-03-20T09:00:00",
    assignedTo: "3",
    assignedToUserName: "Mike Maintenance",
    assignedAt: "2026-03-20T09:30:00",
    completedAt: "2026-03-20T11:00:00",
    closedAt: "2026-03-20T14:00:00",
    photos: [],
    resolution: {
      actionTaken: "Replaced faulty sensor and reset controller",
      partsUsed: "Sensor P/N: 1234-ABC",
      timeSpent: 1.5,
      rootCause: "Sensor failure due to age",
      resolvedBy: "3",
      resolvedAt: "2026-03-20T11:00:00",
    },
  },
  {
    id: "5",
    tagId: "ANO-20260319-0001",
    category: "6",
    categoryName: "Safety Hazard",
    machineId: "4",
    machineName: "Conveyor Belt System",
    description: "Emergency stop button not working. Safety guard missing.",
    priority: "Critical",
    status: "Closed",
    pillar: "Safety",
    createdBy: "1",
    createdByUserName: "John Operator",
    createdAt: "2026-03-19T07:00:00",
    assignedTo: "3",
    assignedToUserName: "Mike Maintenance",
    assignedAt: "2026-03-19T07:30:00",
    completedAt: "2026-03-19T10:00:00",
    closedAt: "2026-03-19T15:00:00",
    photos: [],
    resolution: {
      actionTaken:
        "Replaced emergency stop button and installed new safety guard",
      partsUsed: "E-stop button, safety guard kit",
      timeSpent: 3,
      rootCause: "Worn out components",
      resolvedBy: "3",
      resolvedAt: "2026-03-19T10:00:00",
    },
  },
];
